### ISSUE TITLE
workflow in python

### ISSUE THREAD

**Issue by itsabhianant** [itsabhianant/t_shirts#1]
Even after confirming an order the program instead of quitting restarts itself. I know I messed somewhere in the while loop, but I can't figure out where (Actually I did, but I want someone to contribute to my code :]). Feel free to make changes in the code and send me a PR.:]

**Comment by shanebird92** [comment]
Hi @itsabhianant,
I came across your enhancement and wanted to help out :) 
I know why your code loops and I have a have a suggestion for the if statements, could this be assigned to me?

**Comment by itsabhianant** [comment]
Yeah sure...
